- name: Common setup
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common

- name: Monitoring setup
  hosts: monitoring
  gather_facts: true
  become: true
  roles:
    - monitoring

- name: App stress-ng setup
  hosts: app
  gather_facts: true
  become: true
  roles:
    - app
