common_node_exporter_version: "1.11.1"
common_node_exporter_release_base_url: "https://github.com/prometheus/node_exporter/releases/download"
common_node_exporter_download_url: >-
  {{ common_node_exporter_release_base_url
    ~ '/v' ~ common_node_exporter_version
    ~ '/node_exporter-' ~ common_node_exporter_version
    ~ '.linux-amd64.tar.gz' }}
common_node_exporter_user: "node_exporter"
common_node_exporter_group: "node_exporter"
common_node_exporter_archive_path: "/tmp/node_exporter-{{ common_node_exporter_version }}.linux-amd64.tar.gz"
common_node_exporter_extract_dir: "/tmp/node_exporter-{{ common_node_exporter_version }}.linux-amd64"
